### ISSUE TITLE
scalability on number of cores/threads?

### ISSUE THREAD

**Issue by Tagar** [OpenMP/sources#2]
Are there any known issues on scalability in terms of number of 
cores/threads for OpenMP? 

Let's say if we have 96 threads on a single server - would this scale up? 
We're using some R libraries that use OpenMP 
and with higher thread counts see some delays and generally 
unexpected issues with scaling things up.

**Comment by mjklemm** [comment]
Please note that this is not the right place to ask such a question.  Forums like Stack Overflow would be a better place for such questions.  Please make sure that you give as many details about your algorithm and the problem you are trying to solve, so that the community can provide useful hints.

Let me try to give a high-level answer though. There's nothing particular in the OpenMP API that precludes scalability.  Overall, this is a programming model and you would have to ask the question such that it ask "Is my algorithm the way I express it using OpenMP construct scalable using this OpenMP implementation?"
